---
title: "R Notebook"
output: html_notebook
---

```{r}
library(scibet)
library(tidyverse)
library(ggplot2)
```


##### KS test
```{r, fig.width=5, fig.height=3.5}
data.path <- "/home/pauling/projects/01_classifier/01_data/15_revise/02.CrossValidationData"
out.path <- "/home/pauling/projects/01_classifier/04_figures/03_KStest/02.log.ds"

for (f in 1:length(files)) {
  print(f)
  matr <- readr::read_rds(file.path(data.path, files[f]))
  title.name <- stringr::str_remove(files[f], ".rds.gz")
  matr <- matr %>% dplyr::filter(!is.na(label))
  matr[,-ncol(matr)] <- 1000000*matr[,-ncol(matr)]/rowSums(matr[,-ncol(matr)])
  ent.res <- dsgene(matr)
  ent.res$Total <- log(ent.res$Total)
  a <- ks.test(ent.res$Total, y = "rnorm")
  
  if(a$p.value == 0){
    a$p.value = "< 2.2e-16"
  }else{
    a$p.value = paste0("= ", a$p.value)
  }
  
  ggplot(ent.res, aes(Total)) +
    geom_density() +
    theme_classic() +
    theme(
        axis.title = element_text(size = 15),
        axis.text = element_text(size = 15),
        legend.title = element_text(size = 0),
        legend.text = element_text(size = 15),
        axis.text.y = element_text(color="black"),
        axis.text.x = element_text(color="black")
    ) +
    labs(
        x = "log(ds)",
        y = "Density"
    ) +
    labs(title = title.name, subtitle = paste0("p.value ", a$p.value)) +
    theme(plot.title = element_text(hjust = 0.5, size = 15), 
          plot.subtitle = element_text(hjust = 0.5, size = 15)) -> p
  
  ggsave(plot = p, filename = paste0(title.name,".pdf"), path = out.path, width = 5, height = 3.5, units = "in")
}
```
