# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DsGene <- function(expr_r, label_r, as_df, num_top, additional, n_threads) {
    .Call(`_scibet_DsGene`, expr_r, label_r, as_df, num_top, additional, n_threads)
}

GenProb <- function(expr_r, label_r, geneset_r, n_threads) {
    .Call(`_scibet_GenProb`, expr_r, label_r, geneset_r, n_threads)
}

Gambler <- function(expr_r, prob_r, ret_tab, n_threads) {
    .Call(`_scibet_Gambler`, expr_r, prob_r, ret_tab, n_threads)
}

GenEntr <- function(expr_r, window, n_threads) {
    .Call(`_scibet_GenEntr`, expr_r, window, n_threads)
}

NullTest <- function(ref_r, query_r, null_r, label_r, n_feat, n_threads) {
    .Call(`_scibet_NullTest`, ref_r, query_r, null_r, label_r, n_feat, n_threads)
}

